// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5qx7SiEYyKwrBe_PJ0t7W4JAfv1IWrx8',
    appId: '1:457439302188:web:53b9aa8eecbf3d8fbf3789',
    messagingSenderId: '457439302188',
    projectId: 'route-65-app',
    authDomain: 'route-65-app.firebaseapp.com',
    storageBucket: 'route-65-app.firebasestorage.app',
    measurementId: 'G-B4MJHNNSYN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXGieMy7rwrxjcveeyCJfOtfTLy97y1Gk',
    appId: '1:457439302188:ios:8914f5847a1e3014bf3789',
    messagingSenderId: '457439302188',
    projectId: 'route-65-app',
    storageBucket: 'route-65-app.firebasestorage.app',
    androidClientId: '457439302188-atspi0pjmanut46a1857ngiaajugdbm1.apps.googleusercontent.com',
    iosClientId: '457439302188-ctjdqq38p45taku8h6r3hhom9ej09b8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.route65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYv46xJg5TaRT7L7KfaPlXKAh0s1FaVo',
    appId: '1:457439302188:android:242a73fd608253e2bf3789',
    messagingSenderId: '457439302188',
    projectId: 'route-65-app',
    storageBucket: 'route-65-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5qx7SiEYyKwrBe_PJ0t7W4JAfv1IWrx8',
    appId: '1:457439302188:web:53b9aa8eecbf3d8fbf3789',
    messagingSenderId: '457439302188',
    projectId: 'route-65-app',
    authDomain: 'route-65-app.firebaseapp.com',
    storageBucket: 'route-65-app.firebasestorage.app',
    measurementId: 'G-B4MJHNNSYN',
  );

}